### ISSUE TITLE
minor README change: 600 permission doesn't work with Docker's -v

### ISSUE THREAD

**Issue by rhwinter** [helgeerbe/certbot-dns-ionos#12]
Hi there,
this is super minor, but took me a while to figure out and it would be nice if the `README.rst` had the correct information so others are not stuck like I was.

Essentially:
```
chmod 600 /etc/letsencrypt/.secrets
```
will make the file unreadable by Docker, since apparently it has to be executable (for the `-v` flag to work), both occurences of `chmod 600` in the `README.rst` file (lines 77 and 132) should be replaced by `chmod 700`.

Thanks a lot for the package, it works great :)

**Comment by helgeerbe** [comment]
Hi @rhwinter, Thanks for the feedback. You are right. `/etc/letsencrypt/secrets` should be changed to `chmod 700`. But the credential file should have `600` permissions.  Or do I have missed something? So I will change line 132, but line 77 shouldn't be changed. Maybe I will explain that folders needs the execute permission.
