### ISSUE TITLE
Snap install

### ISSUE THREAD

**Issue by hacknisty** [helgeerbe/certbot-dns-ionos#17]
Hi,

I wonder if you would be able to publish this plugin to snap store ?

I think lot of people are using certbot with snap, and it would make things a lot easier if this plugin is available through snap store.

What do you think ?

Best regards,

**Comment by Chris-Greaves** [comment]
I second this!

I tried using this plugin before and couldn't get it to work with snap, so I ended up using the manual hooks to do this for me.
Unfortuantly, I deleted these hooks now and I'm back here again.

**Comment by helgeerbe** [comment]
Hi, problem is, that I don't use snap and have no experience with it. In #14 there you find a link to a guide to create a snap plugin. Maybe you can try this?

I can support you, but have in the moment only limited resources to work on it. I use docker and find it extremely easy. If you like, I can share my scripts.

**Comment by Chris-Greaves** [comment]
I might have a look at this tonight and see if I can spare some time to implement it for you. 

I figured that you probably used the docker method otherwise you would have raised this yourself a while ago. Thank you for linking #14, I will do my best to keep investigating!

**Comment by OriginaldCrypt** [comment]
Hi, @Chris-Greaves , did you have any success with porting this plugin to Snapcraft? I am one of the certbot snap users, recently switched to IONOS as my DNS provider and I am totally stuck.

BR

**Comment by Chris-Greaves** [comment]
I'm very sorry @OriginaldCrypt, I completely missed your comment until I was going through my mentions today.

I have since moved from IONOS to Cloudflare, it's a shame someone else hasn't picked this up in the meantime. 😢

**Comment by DorianCoding** [comment]
> I'm very sorry @OriginaldCrypt, I completely missed your comment until I was going through my mentions today.
> 
> I have since moved from IONOS to Cloudflare, it's a shame someone else hasn't picked this up in the meantime. 😢

I've tried today to create a snap thanks to certbot instructions but it does not work on my VM :( so I had to get it through pip.

**Comment by DorianCoding** [comment]
Hello back,

I've requested the name and create the snap version on the fork: https://github.com/DorianCoding/certbot-dns-ionos

If it is accepted, I'II publish the snap, if you agree.

**Comment by helgeerbe** [comment]
Thanks for creating the Snap version. I don't use snap at all and had no time to find out, how to create the package.

**Comment by helgeerbe** [comment]
Thanks @DorianCoding for providing the snap code and making this plugin available in the snap store.

Snap is contained in 2024.10.19
