### ISSUE TITLE
No record added to domain

### ISSUE THREAD

**Issue by florohaltero** [helgeerbe/certbot-dns-ionos#21]
Hey,

Is this plugin still working? 
The certificate was successfully created but there is no new DNS record on my domain.
And I also should see the ssl certificate on ionos after that, I am right?
All the docs thats I found from Ionos to add own ssl certificate aren't really useful.. 
https://www.ionos.de/hilfe/ssl-zertifikate/benutzerverwaltetes-ssl-zertifikat-einrichten/benutzerverwaltetes-ssl-zertifikat-einrichten-ssl-starter-ssl-starter-wildcard/

The title says its possible, but they are only writing about the IONOS SSL certifcates..

Thanks and best regards

**Comment by helgeerbe** [comment]
Hi @florohaltero, yes the plugin is working. But I guess you don't have the right understanding what it does.

The TXT DNS record is only temporarily created to "proof" that you are the owner of the domain. The certificates are stored locally, not somewhere on a ionos vault. You have to deploy them to your server(s) which have to use them.

**Comment by florohaltero** [comment]
Hey thanks for the quick reply. 
Yes you right I didn't have the right understanding, but its clear now. 
I thought a could deploy the certs to the ionos hosted webserver but thats not working and I have to buy a starter ssl.

Thanks and best regards

**Comment by helgeerbe** [comment]
Of course you can deploy the certs to your ionos hosted webserver! Certbot provides a hook, where you can put your own deployment script. So e. g. after generation/renewal of the certificates you can copy the certs via scp on your websserver.
