### ISSUE TITLE
IONOS Endpoint

### ISSUE THREAD

**Issue by dim-0** [helgeerbe/certbot-dns-ionos#26]
Thanks for your work on this!

Is there any reference towards the IONOS Endpoint?
I can't find any potential source of information around what possible endpoints could be configured, and how it may be used.
Could you please provide this context in the README?

**Comment by DorianCoding** [comment]
Hello,

There is this: https://developer.hosting.ionos.com/docs/dns

There is one endpoint for now but may change in the future.
