### ISSUE TITLE
Certbot v3.0.0

### ISSUE THREAD

**Issue by DorianCoding** [helgeerbe/certbot-dns-ionos#28]
Hello,

Certbot 3.0 has been released : https://github.com/certbot/certbot/releases/tag/v3.0.0

I have rebuilded the snap and published it. It works well.
You can update your pip package if some issues are encountered. Python 3.8 is still not deprecated. When done, you can make a pull request on my repo.

Thanks.

**Comment by helgeerbe** [comment]
Thanks for the info. With release 2024.11.09 I bumped certbot dependency to >= 3.0.0
